version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: test-sep-mongo
        ports:
            - "27017:27017"
    
    app:
        build: .
        container_name: test-sep-app
        depends_on: 
            - mongodb
        ports:
            - "5000:5000"